apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: miroslavbg/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: miroslavbg/client
      context: client
      sync:
        manual:
          - src: app/**/*.tsx      
            dest: .
          - src: app/**/*.ts      
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}