import axios from "axios";
import { headers } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import ClientSideWrapper from "./components/ClientSideWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const getUser = async (cookieHeader: string) => {
    try {
        const { data } = await axios.get(
            "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/users/currentuser",
            {
                headers: {
                    Host: "localhost",
                    Cookie: cookieHeader,
                },
            }
        );
        return data;
    } catch (error) {
        return null;
    }
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const headersList = headers();
    const cookieHeader = headersList.get("cookie") || "";
    const userData = await getUser(cookieHeader);

    return (
        <html lang="en" data-theme="myDarkTheme">
            <body className={inter.className}>
                <ClientSideWrapper initialUserData={userData} />
                {children}
            </body>
        </html>
    );
}
