// app/layout.tsx
"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "./context/AuthContext";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="bg-main-black-color" >
            <body className={inter.className}>
                <AuthProvider>
                    <Header />
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
